@extends('layouts.app')
@section('title','Buat Akun Outlet — Docan') @section('body-class','login-body')
@section('content')
<main class="register-shell"><section class="register-panel"><a href="{{ route('login') }}" class="back-btn" aria-label="Kembali">←</a><div class="mobile-brand visible"><span class="brand-mark">D</span><b>Docan</b></div><span class="eyebrow green">DAFTAR OUTLET</span><h1>Buat akun outlet</h1><p class="muted">Satu akun Owner untuk mulai mengatur kasir, produk, stok, dan laporan.</p>@if($errors->any())<div class="alert error">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('register.submit') }}" class="register-form">@csrf
<div class="form-row"><div class="form-group"><label for="outlet_name">Nama outlet</label><input id="outlet_name" name="outlet_name" value="{{ old('outlet_name') }}" maxlength="120" required></div><div class="form-group"><label for="owner_name">Nama pemilik</label><input id="owner_name" name="owner_name" value="{{ old('owner_name') }}" maxlength="120" required></div></div>
<div class="form-row"><div class="form-group"><label for="login_id">User Login</label><input id="login_id" name="login_id" value="{{ old('login_id') }}" placeholder="Contoh: TOKO-001" autocapitalize="characters" maxlength="40" required><small>Digunakan untuk masuk ke Docan.</small></div><div class="form-group"><label for="rs_number">Nomor RS</label><input id="rs_number" name="rs_number" value="{{ old('rs_number') }}" inputmode="numeric" autocomplete="off" pattern="[0-9]{6,20}" placeholder="Contoh: 12345678" required><small>Gunakan 6–20 angka tanpa spasi.</small></div></div>
<div class="form-row"><div class="form-group"><label for="password">Kata sandi</label><div class="password-field"><input id="password" type="password" name="password" autocomplete="new-password" minlength="8" required><button type="button" data-toggle-password data-target="password" aria-label="Tampilkan kata sandi"><svg viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.7"/></svg></button></div><small class="password-requirements" id="password-requirements">Minimal 8 karakter, huruf besar-kecil, angka, dan simbol.</small></div><div class="form-group"><label for="password_confirmation">Ulangi kata sandi</label><div class="password-field"><input id="password_confirmation" type="password" name="password_confirmation" autocomplete="new-password" minlength="8" required><button type="button" data-toggle-password data-target="password_confirmation" aria-label="Tampilkan ulang kata sandi"><svg viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.7"/></svg></button></div><small class="password-match" id="password-match">Masukkan ulang kata sandi.</small></div></div>
<label class="consent-field"><input id="terms" type="checkbox" name="terms" value="1" @checked(old('terms'))><span>Saya telah membaca dan menyetujui <a href="{{ route('legal.terms') }}" target="_blank">Syarat dan Ketentuan</a> serta <a href="{{ route('legal.privacy') }}" target="_blank">Kebijakan Privasi Docan</a>.</span></label>
<button class="primary-btn" id="register-submit" type="submit" disabled>Daftar Sekarang</button><p class="login-link">Sudah memiliki akun? <a href="{{ route('login') }}">Masuk</a></p></form></section></main>
<script>document.addEventListener('DOMContentLoaded',()=>{const p=document.querySelector('#password'),c=document.querySelector('#password_confirmation'),m=document.querySelector('#password-match'),r=document.querySelector('#password-requirements'),t=document.querySelector('#terms'),s=document.querySelector('#register-submit');const validate=()=>{const started=p.value!=='';const secure=p.value.length>=8&&/[a-z]/.test(p.value)&&/[A-Z]/.test(p.value)&&/\d/.test(p.value)&&/[^A-Za-z0-9]/.test(p.value);r.classList.toggle('valid',secure);r.classList.toggle('invalid',started&&!secure);r.textContent=secure?'✓ Kata sandi memenuhi standar keamanan.':(started?'Kata sandi belum memenuhi semua syarat.':'Minimal 8 karakter, huruf besar-kecil, angka, dan simbol.');const same=c.value!==''&&p.value===c.value;c.setCustomValidity(c.value!==''&&!same?'Kata sandi belum sama.':'');m.classList.toggle('valid',same);m.classList.toggle('invalid',c.value!==''&&!same);m.textContent=c.value===''?(started?'Ulangi kata sandi untuk memastikan sudah sama.':'Masukkan ulang kata sandi.'):(same?'✓ Kata sandi sudah sama.':'Kata sandi belum sama.');s.disabled=!(secure&&same&&t.checked);};p.addEventListener('input',validate);c.addEventListener('input',validate);t.addEventListener('change',validate);validate();});</script>
@endsection
