<?php
namespace App\Http\Controllers;
use App\Models\{BusinessCategory,BusinessContact,BusinessEntry,Product,Transaction}; use Illuminate\Http\Request;
class BusinessController extends Controller {
 private const ENTRIES=['purchase','cash-in','cash-out','receivable','payable']; private const CONTACTS=['customer','supplier'];
 public function dashboard(){return redirect()->route('business.relations');}
 public function relations(Request $r){$id=$r->user()->outlet_id;return view('business.relations',['customerCount'=>BusinessContact::where('outlet_id',$id)->where('type','customer')->count(),'supplierCount'=>BusinessContact::where('outlet_id',$id)->where('type','supplier')->count(),'receivableTotal'=>BusinessEntry::where('outlet_id',$id)->where('type','receivable')->where('status','open')->sum('amount'),'payableTotal'=>BusinessEntry::where('outlet_id',$id)->where('type','payable')->where('status','open')->sum('amount')]);}
 public function module(Request $r,string $module){abort_unless(in_array($module,[...self::ENTRIES,...self::CONTACTS,'categories'],true),404);$id=$r->user()->outlet_id;$items=in_array($module,self::CONTACTS,true)?BusinessContact::where('outlet_id',$id)->where('type',$module)->latest()->paginate(20):($module==='categories'?BusinessCategory::where('outlet_id',$id)->latest()->paginate(20):BusinessEntry::with('contact')->where('outlet_id',$id)->where('type',$module)->latest('entry_date')->paginate(20));$contacts=BusinessContact::where('outlet_id',$id)->orderBy('name')->get();return view('business.module',compact('module','items','contacts'));}
 public function contact(Request $r,BusinessContact $contact){abort_unless($contact->outlet_id===$r->user()->outlet_id,404);$entries=BusinessEntry::where('outlet_id',$r->user()->outlet_id)->where('contact_id',$contact->id)->latest('entry_date')->paginate(20);return view('business.contact',compact('contact','entries'));}
 public function store(Request $r,string $module){$id=$r->user()->outlet_id;if(in_array($module,self::CONTACTS,true)){$d=$r->validate(['name'=>['required','string','max:120'],'phone'=>['nullable','string','max:24'],'address'=>['nullable','string','max:500']]);BusinessContact::create([...$d,'outlet_id'=>$id,'type'=>$module]);}elseif($module==='categories'){$d=$r->validate(['name'=>['required','string','max:100']]);BusinessCategory::firstOrCreate(['outlet_id'=>$id,'kind'=>'product','name'=>$d['name']]);}else{abort_unless(in_array($module,self::ENTRIES,true),404);$d=$r->validate(['description'=>['required','string','max:180'],'amount'=>['required','integer','min:1'],'entry_date'=>['required','date'],'due_date'=>['nullable','date'],'contact_id'=>['nullable','exists:business_contacts,id'],'status'=>['nullable','in:open,completed']]);BusinessEntry::create([...$d,'outlet_id'=>$id,'user_id'=>$r->user()->id,'type'=>$module,'status'=>$d['status']??'completed']);}return back()->with('success','Data berhasil disimpan.');}
}
