@extends('layouts.app')
@section('title',($product->exists?'Edit':'Tambah').' Produk — Docan') @section('body-class','pos-body')
@section('content')
<div class="app-shell product-page"><header class="topbar"><a href="{{ route('products.index') }}" class="back-btn">←</a><div class="brand"><div><b>{{ $product->exists ? 'Edit produk' : 'Tambah produk' }}</b><small>{{ auth()->user()->outlet?->name }}</small></div></div></header>
<main class="product-form-main"><div class="page-title"><div><span class="eyebrow green">KATALOG OUTLET</span><h1>{{ $product->exists ? 'Perbarui produk' : 'Produk baru' }}</h1><p>Produk ini hanya tersedia untuk outlet Anda.</p></div></div>@if($errors->any())<div class="alert error">{{ $errors->first() }}</div>@endif
<form class="product-form" data-existing='@json($existingPackages)' data-product-id="{{ $product->id }}" method="POST" action="{{ $product->exists ? route('products.update',$product) : route('products.store') }}">@csrf @if($product->exists) @method('PUT') @endif
<div class="form-row"><div class="form-group"><label for="operator">1. Operator / layanan</label><select id="operator" name="operator" required>@foreach($operators as $operator)<option @selected(old('operator',$product->operator ?? request('operator'))===$operator)>{{ $operator }}</option>@endforeach</select></div><div class="form-group"><label for="category">2. Jenis produk</label><select id="category" name="category" required>@foreach($categories as $category)<option @selected(old('category',$product->category ?: request('category','Voucher Internet'))===$category)>{{ $category }}</option>@endforeach</select></div></div>
<div class="accessory-builder" id="accessory-builder" hidden><h3>Detail aksesoris</h3><p>Masukkan nama barang yang mudah dikenali kasir.</p><div class="form-group"><label for="custom-name">Nama aksesoris</label><input id="custom-name" name="name" value="{{ old('name',$product->operator==='AKSESORIS'?$product->name:'') }}" placeholder="Contoh: Kabel Data Type-C"></div></div><div class="package-builder" id="package-builder"><h3>Detail paket</h3><p>Nama produk dibuat otomatis agar format seluruh outlet konsisten.</p><div class="form-row"><div class="form-group"><label for="quota_gb">3. Kuota internet</label><select id="quota_gb" name="quota_gb">@foreach($quotas as $quota)<option value="{{ $quota }}" @selected((float)old('quota_gb',$product->quota_gb ?: 1)===(float)$quota)>{{ number_format($quota, $quota == (int)$quota ? 0 : 1, ',', '.') }} GB</option>@endforeach</select></div><div class="form-group"><label for="validity_days">4. Masa aktif</label><select id="validity_days" name="validity_days">@foreach($validityDays as $day)<option value="{{ $day }}" @selected((int)old('validity_days',$product->validity_days ?: 1)===$day)>{{ $day }} Hari</option>@endforeach</select></div></div><div class="generated-name"><span>Nama yang tampil</span><strong id="generated-product-name">1GB · 1 Hari</strong></div><div class="duplicate-warning" id="duplicate-warning" hidden><b>Produk sudah ada</b><span>Produk dengan detail dan harga modal yang sama sudah tersedia.</span></div></div>
<div class="price-panel"><h3>Harga & keuntungan</h3><div class="form-row"><div class="form-group money"><label for="cost_price">Modal</label><span>Rp</span><input id="cost_price" name="cost_price" type="text" inputmode="numeric" data-money-input value="{{ number_format((int)old('cost_price',$product->cost_price ?? 0),0,'','.') }}" required></div><div class="form-group money"><label for="selling_price">Harga jual</label><span>Rp</span><input id="selling_price" name="selling_price" type="text" inputmode="numeric" data-money-input value="{{ number_format((int)old('selling_price',$product->selling_price ?? 0),0,'','.') }}" required></div></div><div class="profit-preview"><span>Estimasi untung per item</span><strong id="profit-preview">Rp 0</strong></div></div>
<div class="form-row stock-row"><div class="form-group"><label for="stock">Stok tersedia</label><input id="stock" name="stock" type="number" min="0" value="{{ old('stock',$product->stock ?? 0) }}" required></div><label class="switch-field"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$product->exists?$product->is_active:true))><span></span><div><b>Produk aktif</b><small>Tampilkan di kasir</small></div></label></div>
<div class="form-actions"><button class="primary-btn" type="submit">{{ $product->exists ? 'Simpan perubahan' : 'Tambahkan produk' }}</button></div></form></main>@include('components.mobile-nav')</div>
@endsection
