@extends('layouts.app')
@section('title','Produk — Docan') @section('body-class','pos-body')
@section('content')
<div class="app-shell product-page"><header class="topbar"><a href="{{ route('pos') }}" class="back-btn">←</a><div class="brand"><div><b>Kelola Produk</b><small>{{ auth()->user()->outlet?->name }}</small></div></div><a class="header-add always" href="{{ route('products.create') }}">＋ Tambah</a></header>
<main class="products-main">@if(session('success'))<div class="toast success">✓ {{ session('success') }}</div>@endif<div class="page-title"><div><span class="eyebrow green">INVENTORI OUTLET</span><h1>{{ request('stock')?'Tambah stok':'Produk & stok' }}</h1><p>{{ request('stock')?'Masukkan jumlah stok tanpa membuka halaman edit.':'Atur modal, harga jual, dan stok outlet.' }}</p></div><a class="primary-small" href="{{ route('products.create') }}">＋ Tambah produk</a></div>
<div class="stat-grid"><div><span>Total produk</span><strong>{{ number_format($stats->total) }}</strong></div><div><span>Sisa stok</span><strong>{{ number_format($stats->stock) }}</strong></div><div><span>Nilai modal stok</span><strong>Rp {{ number_format($stats->value,0,',','.') }}</strong></div></div>
<form class="product-filters"><div class="product-search"><span>⌕</span><input name="q" value="{{ request('q') }}" placeholder="Cari produk..."></div><select name="operator" onchange="this.form.submit()"><option value="">Semua operator</option>@foreach($operators as $operator)<option @selected(request('operator')===$operator)>{{ $operator }}</option>@endforeach</select></form>
<div class="inventory-list">@forelse($products as $product)<article class="inventory-card"><div class="stock-badge {{ $product->stock < 5 ? 'low' : '' }}">{{ $product->stock }}<small>stok</small></div><div class="inventory-info"><div><span>{{ $product->operator }} · {{ $product->category }}</span>@unless($product->is_active)<i>Nonaktif</i>@endunless</div><h3>{{ $product->name }}</h3><p>Modal <b>Rp {{ number_format($product->cost_price,0,',','.') }}</b> → Jual <b>Rp {{ number_format($product->selling_price,0,',','.') }}</b></p><em>Untung Rp {{ number_format($product->profit,0,',','.') }} / item</em></div>@if(request('stock'))<form class="inventory-stock-form" method="POST" action="{{ route('products.stock',$product) }}">@csrf<input type="number" name="quantity" min="1" value="1" aria-label="Jumlah stok"><button>+ Stok</button></form>@else<div class="card-actions"><a href="{{ route('products.edit',$product) }}">Edit</a><form method="POST" action="{{ route('products.destroy',$product) }}" onsubmit="return confirm('Hapus produk ini?')">@csrf @method('DELETE')<button>Hapus</button></form></div>@endif</article>@empty<div class="empty-state"><b>Produk tidak ditemukan</b><p>Coba kata kunci lain atau tambahkan produk baru.</p></div>@endforelse</div>
@if($products->hasPages())<nav class="pager" aria-label="Navigasi halaman"><a class="{{ $products->onFirstPage() ? 'disabled' : '' }}" href="{{ $products->previousPageUrl() ?: '#' }}">← Sebelumnya</a><span>Halaman {{ $products->currentPage() }} dari {{ $products->lastPage() }}</span><a class="{{ $products->hasMorePages() ? '' : 'disabled' }}" href="{{ $products->nextPageUrl() ?: '#' }}">Berikutnya →</a></nav>@endif</main>
@include('components.mobile-nav')</div>
@endsection
