@extends('layouts.app')
@section('title','Produk — Docan') @section('body-class','pos-body')
@section('content')
@php($isProductLanding = !request('group') && !request('operator') && request('view')!=='all')
@php($isBalanceGroup = in_array(request('group'),['recharge','wallet'],true))
@php($canAddForSelection = auth()->user()->isOwner() && request('operator'))
@php($addCategory = $isBalanceGroup?'Saldo Provider':(request('group')==='accessory'?'Aksesoris HP':'Voucher Internet'))
@php($addParams = ['operator'=>request('operator'),'group'=>request('group'),'category'=>$addCategory,'locked'=>1,'return_group'=>request('group'),'return_operator'=>request('operator')])
@php($headerBack = request('group') === 'accessory' ? route('products.index') : (request('operator') ? route('products.index',array_filter(['group'=>request('group'),'stock'=>request('stock')])) : (request('group') ? route('products.index',array_filter(['stock'=>request('stock')])) : route('pos'))))
<div class="app-shell product-page">
<header class="topbar"><a href="{{ $headerBack }}" class="back-btn">←</a><div class="brand"><div><b>Kelola Produk</b><small>{{ auth()->user()->outlet?->name }}</small></div></div>@if($canAddForSelection)<a class="header-add always" href="{{ route('products.create',$addParams) }}">＋ {{ $isBalanceGroup ? 'Tambah saldo' : 'Tambah' }}</a>@endif</header>
<main @class(['products-main','provider-detail'=>request('operator') || request('view')==='all'])>
@if(session('success'))<div class="toast success">✓ {{ session('success') }}</div>@endif
@if($isProductLanding)
<section class="product-group-heading"><span class="eyebrow green">KATALOG OUTLET</span><h1>Pilih kelompok produk</h1><p>Buka kelompok yang ingin kamu atur agar daftar produk tetap ringkas.</p></section>
<div class="product-group-grid">
    <a class="product-group-card" href="{{ route('products.index',array_filter(['group'=>'provider','stock'=>request('stock')])) }}"><span class="product-group-icon"><svg viewBox="0 0 24 24"><rect x="6" y="3" width="12" height="18" rx="3"/><path d="M9 7h6M9 11h2M13 11h2M9 15h2M13 15h2"/></svg></span><div><b>Produk Provider</b><small>{{ number_format($serviceGroups['provider']) }} produk voucher fisik dan kartu paket</small></div></a>
    <a class="product-group-card" href="{{ route('products.index',array_filter(['group'=>'recharge','stock'=>request('stock')])) }}"><span class="product-group-icon"><svg viewBox="0 0 24 24"><path d="M13 2 5 13h6l-1 9 9-12h-6z"/></svg></span><div><b>Pulsa & Paket Tembak</b><small>{{ number_format($serviceGroups['recharge']) }} saldo channel · Rp {{ number_format($serviceBalance,0,',','.') }}</small></div></a>
    <a class="product-group-card" href="{{ route('products.index',array_filter(['group'=>'wallet','stock'=>request('stock')])) }}"><span class="product-group-icon"><svg viewBox="0 0 24 24"><path d="M4 6.5h14a2 2 0 0 1 2 2V18H4a2 2 0 0 1-2-2V6a3 3 0 0 1 3-3h12"/><path d="M16 11h4v4h-4a2 2 0 0 1 0-4z"/></svg></span><div><b>E-Wallet</b><small>{{ number_format($serviceGroups['wallet']) }} akun saldo DANA, OVO, GoPay, Maxim, dan lainnya</small></div></a>
    <a class="product-group-card" href="{{ route('products.index',array_filter(['group'=>'accessory','operator'=>'AKSESORIS','stock'=>request('stock')])) }}"><span class="product-group-icon"><svg viewBox="0 0 24 24"><path d="m14.7 6.3 3-3a4 4 0 0 1-5.6 5.6l-6.8 6.8a2 2 0 1 0 3 3l6.8-6.8a4 4 0 0 1 5.6-5.6l-3 3z"/></svg></span><div><b>Aksesoris HP</b><small>{{ number_format($serviceGroups['accessory']) }} kabel, charger, casing, dan lainnya</small></div></a>
</div>
<section class="stock-history-section">
    <div class="stock-history-heading"><div><span class="eyebrow green">RIWAYAT STOK & SALDO</span><h2>Aktivitas terbaru</h2><p>Semua penambahan, pengurangan, dan penjualan tercatat otomatis.</p></div></div>
    <div class="stock-history-list">
        @forelse($stockMovements as $movement)
        @php($moneyMovement = $movement->category === 'Saldo Provider')
        <article class="stock-history-row">
            <time>{{ $movement->created_at->format('d/m/Y') }}<small>{{ $movement->created_at->format('H:i') }}</small></time>
            <div><b>{{ $movement->product_name }}</b><small>{{ $movement->operator }} · {{ $movement->category }} · {{ $movement->user?->name ?? 'Sistem' }}</small></div>
            <strong class="{{ $movement->quantity < 0 ? 'negative' : 'positive' }}">{{ $movement->quantity > 0 ? '+' : '−' }}{{ $moneyMovement ? 'Rp '.number_format(abs($movement->quantity),0,',','.') : number_format(abs($movement->quantity),0,',','.') }}<small>{{ $moneyMovement ? 'Rp '.number_format($movement->stock_after,0,',','.') : number_format($movement->stock_after,0,',','.').' tersisa' }}</small></strong>
        </article>
        @empty
        <div class="empty-state"><b>Belum ada aktivitas stok</b><p>Riwayat akan muncul setelah stok atau saldo berubah.</p></div>
        @endforelse
    </div>
</section>
@else
<div class="page-title"><div><span class="eyebrow green">INVENTORI OUTLET</span><h1>{{ $isBalanceGroup?'Saldo layanan':(auth()->user()->isFrontliner()?'Stok outlet':(request('stock')?'Tambah stok':'Produk & stok')) }}</h1><p>{{ $isBalanceGroup?'Pantau sisa saldo layanan.':(auth()->user()->isFrontliner()?'Lihat ketersediaan stok. Perubahan stok hanya dapat dilakukan oleh Owner.':(request('stock')?'Masukkan jumlah stok tanpa membuka halaman edit.':'Atur modal, harga jual, dan stok outlet.')) }}</p></div></div>
@php($shownStats = request('group') || request('operator') || request('view')==='all' ? $detailStats : $stats)
<div class="stat-grid"><div><span>{{ $isBalanceGroup?'Jumlah akun saldo':'Total produk' }}</span><strong>{{ number_format($shownStats->total) }}</strong></div><div><span>{{ $isBalanceGroup?'Total saldo':'Sisa stok' }}</span><strong>{{ $isBalanceGroup?'Rp ':'' }}{{ number_format($shownStats->stock,0,',','.') }}</strong></div><div><span>{{ $isBalanceGroup?'Saldo tersedia':'Nilai modal stok' }}</span><strong>Rp {{ number_format($shownStats->value,0,',','.') }}</strong></div></div>
@unless(request('operator') || request('view')==='all')
@if($isBalanceGroup)
<section class="provider-stock-section balance-channel-section"><div class="provider-stock-heading"><div><span class="eyebrow green">RINGKASAN SALDO</span><h2>{{ request('group')==='wallet'?'Pilih E-Wallet':'Pilih channel transaksi' }}</h2><p>Buka layanan untuk melihat dan menambahkan saldo deposit.</p></div></div><div class="provider-stock-grid">@foreach($balanceSummaries as $summary)<a class="provider-stock-card balance-channel-card" href="{{ route('products.index',array_filter(['group'=>request('group'),'operator'=>$summary['operator'],'stock'=>request('stock')])) }}"><div class="provider-stock-title"><span class="provider-summary-logo"><img src="/img/{{ $summary['logo'] }}" alt="{{ $summary['name'] }}"></span><div><b>{{ $summary['name'] }}</b><small>{{ $summary['products'] ? $summary['products'].' akun saldo' : 'Belum dibuat' }}</small></div></div><dl><div><dt>Sisa saldo</dt><dd>Rp {{ number_format($summary['balance'],0,',','.') }}</dd></div><div><dt>Status</dt><dd>{{ $summary['products'] ? 'Aktif' : 'Perlu ditambahkan' }}</dd></div></dl></a>@endforeach</div></section>
@else
<section class="provider-stock-section"><div class="provider-stock-heading"><div><span class="eyebrow green">RINGKASAN STOK</span><h2>Pilih provider</h2><p>Pilih provider untuk membuka rincian seluruh produknya.</p></div></div><div class="provider-stock-grid"><a class="provider-stock-card" href="{{ route('products.index',array_filter(['group'=>request('group'),'view'=>'all','stock'=>request('stock')])) }}"><div class="provider-stock-title"><span class="provider-summary-logo all-logo">D</span><div><b>Semua Provider</b><small>{{ number_format(request('group')==='provider' ? $detailStats->total : $stats->total) }} produk</small></div></div><dl><div><dt>Total stok</dt><dd>{{ number_format(request('group')==='provider' ? $detailStats->stock : $stats->stock) }}</dd></div><div><dt>Nilai modal</dt><dd>Rp {{ number_format(request('group')==='provider' ? $detailStats->value : $stats->value,0,',','.') }}</dd></div></dl></a>@foreach($providerSummaries as $summary)<a class="provider-stock-card" href="{{ route('products.index',array_filter(['group'=>request('group'),'operator'=>$summary['operator'],'stock'=>request('stock')])) }}"><div class="provider-stock-title"><span class="provider-summary-logo"><img src="/img/{{ $summary['logo'] }}" alt="{{ $summary['operator'] }}"></span><div><b>{{ $summary['operator']==='BYU'?'by.U':ucfirst(strtolower($summary['operator'])) }}</b><small>{{ $summary['products'] }} produk</small></div></div><dl><div><dt>Voucher fisik</dt><dd>{{ number_format($summary['voucher']) }}</dd></div><div><dt>Kartu perdana</dt><dd>{{ number_format($summary['package']) }}</dd></div></dl></a>@endforeach</div></section>
@endif
@endunless
@if(request('operator') || request('view')==='all')
<div class="inventory-provider-title"><div><span>{{ $isBalanceGroup?'RINCIAN SALDO':'RINCIAN PRODUK' }}</span><h2>{{ request('operator') ? (request('operator')==='BYU'?'by.U':ucfirst(strtolower(request('operator')))) : 'Semua Provider' }}</h2></div></div>
@unless($isBalanceGroup)
<nav class="inventory-sort" aria-label="Urutkan produk"><a @class(['active'=>!request('sort')]) href="{{ request()->fullUrlWithQuery(['sort'=>null,'page'=>null]) }}">Semua produk</a><a @class(['active'=>request('sort')==='lowest']) href="{{ request()->fullUrlWithQuery(['sort'=>'lowest','page'=>null]) }}">Stok terendah</a><a @class(['active'=>request('sort')==='bestseller']) href="{{ request()->fullUrlWithQuery(['sort'=>'bestseller','page'=>null]) }}">Stok terlaris</a></nav>
<form class="inventory-search" method="GET" action="{{ route('products.index') }}"><input type="hidden" name="group" value="{{ request('group') }}">@if(request('operator'))<input type="hidden" name="operator" value="{{ request('operator') }}">@else<input type="hidden" name="view" value="all">@endif<input name="q" value="{{ request('q') }}" placeholder="Cari nama produk..." aria-label="Cari produk"><button>Cari</button>@if(request('q'))<a href="{{ request()->fullUrlWithQuery(['q'=>null,'page'=>null]) }}">Hapus</a>@endif</form>
@endunless
<div class="inventory-list">@forelse($productGroups as $variants)@php($package=$variants->first()) @php($isBalance=$package->category==='Saldo Provider')<article class="inventory-group"><header><div><span>{{ $package->operator }} · {{ $package->category }}</span><h3>{{ $package->name }}</h3><small>{{ $isBalance ? 'Saldo channel transaksi' : $variants->count().' varian harga' }}</small></div></header><div class="price-variant-list">@foreach($variants as $product)<section class="price-variant-row"><div class="stock-badge {{ !$isBalance && $product->stock < 5 ? 'low' : '' }}">{{ $isBalance ? 'Rp' : number_format($product->stock,0,',','.') }}<small>{{ $isBalance ? number_format($product->stock,0,',','.') : 'stok' }}</small></div><div class="inventory-info">@if($isBalance)<p>Saldo tersedia <b>Rp {{ number_format($product->stock,0,',','.') }}</b></p><em>Saldo dapat ditambah atau dikurangi oleh Owner.</em>@else<p>Modal <b>Rp {{ number_format($product->cost_price,0,',','.') }}</b> · Jual <b>Rp {{ number_format($product->selling_price,0,',','.') }}</b></p><em>Untung Rp {{ number_format($product->profit,0,',','.') }} / item</em>@endif @unless($product->is_active)<i>Nonaktif</i>@endunless</div>@if(auth()->user()->isOwner())<div class="card-actions">@unless($isBalance)<a href="{{ route('products.edit',$product) }}">Edit harga</a>@endunless<form class="quick-stock-form" method="POST" action="{{ route('products.stock',$product) }}">@csrf<input type="text" inputmode="numeric" data-money-input name="quantity" value="{{ number_format($isBalance ? 100000 : 1,0,',','.') }}" required aria-label="{{ $isBalance ? 'Nominal saldo' : 'Jumlah stok' }}"><button name="direction" value="increase">+ {{ $isBalance ? 'Saldo' : 'Stok' }}</button><button class="reduce-stock" name="direction" value="decrease">− {{ $isBalance ? 'Saldo' : 'Stok' }}</button></form><form method="POST" action="{{ route('products.destroy',$product) }}" data-delete-product data-product-name="{{ $package->name }}" data-product-price="{{ $isBalance ? 'Saldo Rp '.number_format($product->stock,0,',','.') : 'Rp '.number_format($product->selling_price,0,',','.') }}">@csrf @method('DELETE')<button type="submit">Hapus</button></form></div>@endif</section>@endforeach</div></article>@empty<div class="empty-state"><b>{{ $isBalanceGroup?'Saldo belum dibuat':'Produk tidak ditemukan' }}</b><p>{{ $isBalanceGroup?'Saldo layanan belum dibuat oleh Owner.':'Belum ada produk pada provider ini.' }}</p></div>@endforelse</div>
@if($products->hasPages())<nav class="pager" aria-label="Navigasi halaman"><a class="{{ $products->onFirstPage() ? 'disabled' : '' }}" href="{{ $products->previousPageUrl() ?: '#' }}">← Sebelumnya</a><span>Halaman {{ $products->currentPage() }} dari {{ $products->lastPage() }}</span><a class="{{ $products->hasMorePages() ? '' : 'disabled' }}" href="{{ $products->nextPageUrl() ?: '#' }}">Berikutnya →</a></nav>@endif
@endif
@endif
</main>
<div class="delete-product-modal" id="delete-product-modal" hidden><div class="delete-product-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-product-title"><span class="delete-product-icon"><svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/></svg></span><small>HAPUS PRODUK</small><h2 id="delete-product-title">Hapus varian harga?</h2><p><b id="delete-product-name"></b><span id="delete-product-price"></span></p><div><button type="button" id="cancel-delete-product">Batal</button><button type="button" id="confirm-delete-product">Ya, hapus</button></div></div></div>
@include('components.mobile-nav')</div>
@endsection
