@extends('layouts.app')
@section('title','Produk — Docan') @section('body-class','pos-body')
@section('content')
<div class="app-shell product-page"><header class="topbar"><a href="{{ route('pos') }}" class="back-btn">←</a><div class="brand"><div><b>Kelola Produk</b><small>{{ auth()->user()->outlet?->name }}</small></div></div>@if(auth()->user()->isOwner())<a class="header-add always" href="{{ route('products.create') }}">＋ Tambah</a>@endif</header>
<main @class(['products-main','provider-detail'=>request('operator') || request('view')==='all'])>@if(session('success'))<div class="toast success">✓ {{ session('success') }}</div>@endif<div class="page-title"><div><span class="eyebrow green">INVENTORI OUTLET</span><h1>{{ request('stock')?'Tambah stok':'Produk & stok' }}</h1><p>{{ request('stock')?'Masukkan jumlah stok tanpa membuka halaman edit.':'Atur modal, harga jual, dan stok outlet.' }}</p></div>@if(auth()->user()->isOwner())<a class="primary-small" href="{{ route('products.create') }}">＋ Tambah produk</a>@endif</div>
@php($shownStats = request('operator') || request('view')==='all' ? $detailStats : $stats)
<div class="stat-grid"><div><span>Total produk</span><strong>{{ number_format($shownStats->total) }}</strong></div><div><span>Sisa stok</span><strong>{{ number_format($shownStats->stock) }}</strong></div><div><span>Nilai modal stok</span><strong>Rp {{ number_format($shownStats->value,0,',','.') }}</strong></div></div>
@unless(request('operator') || request('view')==='all')
<section class="provider-stock-section"><div class="provider-stock-heading"><div><span class="eyebrow green">RINGKASAN STOK</span><h2>Pilih provider</h2><p>Pilih provider untuk membuka rincian seluruh produknya.</p></div></div><div class="provider-stock-grid"><a class="provider-stock-card" href="{{ route('products.index',array_filter(['view'=>'all','stock'=>request('stock')])) }}"><div class="provider-stock-title"><span class="provider-summary-logo all-logo">D</span><div><b>Semua Provider</b><small>{{ number_format($stats->total) }} produk</small></div></div><dl><div><dt>Total stok</dt><dd>{{ number_format($stats->stock) }}</dd></div><div><dt>Nilai modal</dt><dd>Rp {{ number_format($stats->value,0,',','.') }}</dd></div></dl></a>@foreach($providerSummaries as $summary)<a class="provider-stock-card" href="{{ route('products.index',array_filter(['operator'=>$summary['operator'],'stock'=>request('stock')])) }}"><div class="provider-stock-title"><span class="provider-summary-logo"><img src="/img/{{ $summary['logo'] }}" alt="{{ $summary['operator'] }}"></span><div><b>{{ $summary['operator']==='BYU'?'by.U':ucfirst(strtolower($summary['operator'])) }}</b><small>{{ $summary['products'] }} produk</small></div></div><dl><div><dt>Voucher fisik</dt><dd>{{ number_format($summary['voucher']) }}</dd></div><div><dt>Kartu perdana</dt><dd>{{ number_format($summary['package']) }}</dd></div><div><dt>Saldo {{ $summary['channel'] }}</dt><dd>{{ $summary['balance'] > 0 ? 'Rp '.number_format($summary['balance'],0,',','.') : 'Belum diisi' }}</dd></div></dl></a>@endforeach</div></section>
@endunless
@if(request('operator') || request('view')==='all')
<div class="inventory-provider-title"><div><span>RINCIAN PRODUK</span><h2>{{ request('operator') ? (request('operator')==='BYU'?'by.U':ucfirst(strtolower(request('operator')))) : 'Semua Provider' }}</h2></div><a href="{{ route('products.index',array_filter(['stock'=>request('stock')])) }}">Kembali ke provider</a></div>
<nav class="inventory-sort" aria-label="Urutkan produk"><a @class(['active'=>!request('sort')]) href="{{ request()->fullUrlWithQuery(['sort'=>null,'page'=>null]) }}">Semua produk</a><a @class(['active'=>request('sort')==='lowest']) href="{{ request()->fullUrlWithQuery(['sort'=>'lowest','page'=>null]) }}">Stok terendah</a><a @class(['active'=>request('sort')==='bestseller']) href="{{ request()->fullUrlWithQuery(['sort'=>'bestseller','page'=>null]) }}">Stok terlaris</a></nav>
<form class="inventory-search" method="GET" action="{{ route('products.index') }}">@if(request('operator'))<input type="hidden" name="operator" value="{{ request('operator') }}">@else<input type="hidden" name="view" value="all">@endif<input name="q" value="{{ request('q') }}" placeholder="Cari nama produk..." aria-label="Cari produk"><button>Cari</button>@if(request('q'))<a href="{{ request()->fullUrlWithQuery(['q'=>null,'page'=>null]) }}">Hapus</a>@endif</form>
<div class="inventory-list">@forelse($productGroups as $variants)@php($package=$variants->first()) @php($isBalance=$package->category==='Saldo Provider')<article class="inventory-group"><header><div><span>{{ $package->operator }} · {{ $package->category }}</span><h3>{{ $package->name }}</h3><small>{{ $isBalance ? 'Saldo channel transaksi' : $variants->count().' varian harga' }}</small></div></header><div class="price-variant-list">@foreach($variants as $product)<section class="price-variant-row"><div class="stock-badge {{ !$isBalance && $product->stock < 5 ? 'low' : '' }}">{{ $isBalance ? 'Rp' : number_format($product->stock) }}<small>{{ $isBalance ? number_format($product->stock,0,',','.') : 'stok' }}</small></div><div class="inventory-info">@if($isBalance)<p>Saldo tersedia <b>Rp {{ number_format($product->stock,0,',','.') }}</b></p><em>Tambah saldo setiap kali melakukan deposit ke channel.</em>@else<p>Modal <b>Rp {{ number_format($product->cost_price,0,',','.') }}</b> → Jual <b>Rp {{ number_format($product->selling_price,0,',','.') }}</b></p><em>Untung Rp {{ number_format($product->profit,0,',','.') }} / item</em>@endif @unless($product->is_active)<i>Nonaktif</i>@endunless</div><div class="card-actions">@if(auth()->user()->isOwner() && !$isBalance)<a href="{{ route('products.edit',$product) }}">Edit harga</a>@endif<form class="quick-stock-form" method="POST" action="{{ route('products.stock',$product) }}">@csrf<input type="number" name="quantity" min="1" value="{{ $isBalance ? 100000 : 1 }}" required aria-label="{{ $isBalance ? 'Nominal saldo yang ditambahkan' : 'Jumlah stok yang ditambahkan' }}"><button>+ {{ $isBalance ? 'Saldo' : 'Stok' }}</button></form>@if(auth()->user()->isOwner())<form method="POST" action="{{ route('products.destroy',$product) }}" data-delete-product data-product-name="{{ $package->name }}" data-product-price="{{ $isBalance ? 'Saldo Rp '.number_format($product->stock,0,',','.') : 'Rp '.number_format($product->selling_price,0,',','.') }}">@csrf @method('DELETE')<button type="submit">Hapus</button></form>@endif</div></section>@endforeach</div></article>@empty<div class="empty-state"><b>Produk tidak ditemukan</b><p>Belum ada produk pada provider ini.</p></div>@endforelse</div>
@if($products->hasPages())<nav class="pager" aria-label="Navigasi halaman"><a class="{{ $products->onFirstPage() ? 'disabled' : '' }}" href="{{ $products->previousPageUrl() ?: '#' }}">← Sebelumnya</a><span>Halaman {{ $products->currentPage() }} dari {{ $products->lastPage() }}</span><a class="{{ $products->hasMorePages() ? '' : 'disabled' }}" href="{{ $products->nextPageUrl() ?: '#' }}">Berikutnya →</a></nav>@endif
@endif</main>
<div class="delete-product-modal" id="delete-product-modal" hidden><div class="delete-product-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-product-title"><span class="delete-product-icon"><svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/></svg></span><small>HAPUS PRODUK</small><h2 id="delete-product-title">Hapus varian harga?</h2><p><b id="delete-product-name"></b><span id="delete-product-price"></span></p><div><button type="button" id="cancel-delete-product">Batal</button><button type="button" id="confirm-delete-product">Ya, hapus</button></div></div></div>
@include('components.mobile-nav')</div>
@endsection
